# Generated by Django 3.0.3 on 2020-02-26 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and Use special characters in case the given username is repeated', max_length=30, null=True, unique=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and special characters', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_no', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('pin', models.IntegerField(blank=True, help_text='Required. 6 digits or 4 digit number', null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='netbankingapp.Users')),
            ],
        ),
    ]
