# Generated by Django 3.0.3 on 2020-02-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and special characters', max_length=300, null=True),
        ),
    ]
